blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Questions & Discussions
    url: https://github.com/razorvision/safequote.io-React-Only/discussions
    about: Ask questions and discuss ideas with the team
